# Generated by Django 4.1.7 on 2023-05-14 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_issn', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=150)),
                ('author_name', models.CharField(max_length=200)),
                ('book_type', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=255)),
                ('copies', models.IntegerField(default=1)),
                ('format', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('book_add_time', models.TimeField(default=datetime.datetime(2023, 5, 14, 10, 38, 36, 338915, tzinfo=datetime.timezone.utc))),
                ('book_add_date', models.DateField(default=datetime.date(2023, 5, 14))),
            ],
            options={
                'unique_together': {('title', 'author_name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateField(default=datetime.date.today)),
                ('date_due', models.DateField()),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
