# Generated by Django 4.1.7 on 2023-05-14 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 14, 10, 39, 8, 583924, tzinfo=datetime.timezone.utc)),
        ),
    ]
