# Generated by Django 4.1.7 on 2023-05-14 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_book_add_date_alter_book_book_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_add_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
