# Generated by Django 4.1.7 on 2023-05-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_book_add_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(max_length=200),
        ),
    ]
