# Generated by Django 4.1.7 on 2023-05-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
