# Generated by Django 4.1.7 on 2023-05-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
