# Generated by Django 4.1.7 on 2023-04-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('copies_available', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('book_type', models.CharField(max_length=255)),
                ('isbn_issn', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('copies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
